media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Published On, type: date, options: { time: true } }
      - { name: modDatetime, label: Last Modified, type: date, options: { time: true } }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: ogImage, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - name: contact
        label: Contact information
        type: object
        fields:
          - { name: first_name, label: "First name", type: string }
          - { name: last_name,  label: "Last name",  type: string }
          - { name: email,      label: "Email address", type: string }
          - { name: phone,      label: "Phone number",  type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
